import { int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Learning Sessions Table
 * Stores information about each learning session.
 * Sessions are identified by a unique sessionId generated on the frontend and stored in localStorage.
 */
export const learningSessions = mysqlTable("learning_sessions", {
  id: int("id").autoincrement().primaryKey(),
  /** Unique session identifier generated by the frontend (UUID or similar) */
  sessionId: varchar("sessionId", { length: 64 }).notNull().unique(),
  /** The economic topic being studied (e.g., "Supply and Demand", "Inflation") */
  topic: text("topic").notNull(),
  /** Brief description or context provided by the user */
  description: text("description"),
  /** Timestamp when the session was created */
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  /** Timestamp when the session was last updated */
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type LearningSession = typeof learningSessions.$inferSelect;
export type InsertLearningSession = typeof learningSessions.$inferInsert;

/**
 * Chat Logs Table
 * Stores the conversation history between the user and the AI mentor.
 * Each message (user or assistant) is recorded with metadata.
 */
export const chatLogs = mysqlTable("chat_logs", {
  id: int("id").autoincrement().primaryKey(),
  /** Foreign key reference to the learning session */
  sessionId: varchar("sessionId", { length: 64 }).notNull(),
  /** Role of the message sender: "user" or "assistant" */
  role: mysqlEnum("role", ["user", "assistant"]).notNull(),
  /** The actual message content */
  content: text("content").notNull(),
  /** Type of content: "text", "graph_data", "scenario", etc. */
  contentType: varchar("contentType", { length: 64 }).default("text").notNull(),
  /** Optional JSON data for structured responses (e.g., graph coordinates, scenario analysis) */
  metadata: text("metadata"), // Stores JSON stringified data
  /** Timestamp when the message was created */
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ChatLog = typeof chatLogs.$inferSelect;
export type InsertChatLog = typeof chatLogs.$inferInsert;
