import { int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Learning Sessions Table
 * Stores information about each learning session.
 * Sessions are identified by a unique sessionId generated on the frontend and stored in localStorage.
 */
export const learningSessions = mysqlTable("learning_sessions", {
  id: int("id").autoincrement().primaryKey(),
  /** Unique session identifier generated by the frontend (UUID or similar) */
  sessionId: varchar("sessionId", { length: 64 }).notNull().unique(),
  /** The economic topic being studied (e.g., "Supply and Demand", "Inflation") */
  topic: text("topic").notNull(),
  /** Brief description or context provided by the user */
  description: text("description"),
  /** Timestamp when the session was created */
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  /** Timestamp when the session was last updated */
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type LearningSession = typeof learningSessions.$inferSelect;
export type InsertLearningSession = typeof learningSessions.$inferInsert;

/**
 * Chat Logs Table
 * Stores the conversation history between the user and the AI mentor.
 * Each message (user or assistant) is recorded with metadata.
 */
export const chatLogs = mysqlTable("chat_logs", {
  id: int("id").autoincrement().primaryKey(),
  /** Foreign key reference to the learning session */
  sessionId: varchar("sessionId", { length: 64 }).notNull(),
  /** Role of the message sender: "user" or "assistant" */
  role: mysqlEnum("role", ["user", "assistant"]).notNull(),
  /** The actual message content */
  content: text("content").notNull(),
  /** Type of content: "text", "graph_data", "scenario", etc. */
  contentType: varchar("contentType", { length: 64 }).default("text").notNull(),
  /** Optional JSON data for structured responses (e.g., graph coordinates, scenario analysis) */
  metadata: text("metadata"), // Stores JSON stringified data
  /** Timestamp when the message was created */
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ChatLog = typeof chatLogs.$inferSelect;
export type InsertChatLog = typeof chatLogs.$inferInsert;


/**
 * Quizzes Table
 * Stores quiz questions generated by the AI for each learning session.
 */
export const quizzes = mysqlTable("quizzes", {
  id: int("id").autoincrement().primaryKey(),
  /** Foreign key reference to the learning session */
  sessionId: varchar("sessionId", { length: 64 }).notNull(),
  /** The quiz question */
  question: text("question").notNull(),
  /** JSON array of answer options (A), (B), (C), (D) */
  options: text("options").notNull(),
  /** The correct answer key (e.g., "A", "B", "C", "D") */
  correctAnswer: varchar("correctAnswer", { length: 8 }).notNull(),
  /** Explanation of the correct answer */
  explanation: text("explanation"),
  /** User's submitted answer (null if not answered) */
  userAnswer: varchar("userAnswer", { length: 8 }),
  /** Whether the user answered correctly */
  isCorrect: int("isCorrect"),
  /** Difficulty level of the quiz */
  difficulty: mysqlEnum("difficulty", ["easy", "medium", "hard"]).default("medium").notNull(),
  /** Timestamp when the quiz was created */
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Quiz = typeof quizzes.$inferSelect;
export type InsertQuiz = typeof quizzes.$inferInsert;

/**
 * Practice Problems Table
 * Stores practice problems with step-by-step solutions.
 */
export const practiceProblems = mysqlTable("practice_problems", {
  id: int("id").autoincrement().primaryKey(),
  /** Foreign key reference to the learning session */
  sessionId: varchar("sessionId", { length: 64 }).notNull(),
  /** The problem statement */
  problem: text("problem").notNull(),
  /** Step-by-step solution (JSON array of steps) */
  solution: text("solution").notNull(),
  /** Final answer */
  answer: text("answer").notNull(),
  /** Hints for solving the problem (JSON array) */
  hints: text("hints"),
  /** Difficulty level */
  difficulty: mysqlEnum("difficulty", ["easy", "medium", "hard"]).default("medium").notNull(),
  /** Whether the user has completed this problem */
  isCompleted: int("isCompleted").default(0),
  /** Timestamp when the problem was created */
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type PracticeProblem = typeof practiceProblems.$inferSelect;
export type InsertPracticeProblem = typeof practiceProblems.$inferInsert;

/**
 * Learning Notes Table
 * Stores user notes taken during learning sessions.
 */
export const learningNotes = mysqlTable("learning_notes", {
  id: int("id").autoincrement().primaryKey(),
  /** Foreign key reference to the learning session */
  sessionId: varchar("sessionId", { length: 64 }).notNull(),
  /** The note content */
  noteText: text("noteText").notNull(),
  /** Category for organizing notes */
  category: varchar("category", { length: 128 }),
  /** Timestamp when the note was created */
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  /** Timestamp when the note was last updated */
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type LearningNote = typeof learningNotes.$inferSelect;
export type InsertLearningNote = typeof learningNotes.$inferInsert;

/**
 * Session Performance Table
 * Tracks user performance metrics for adaptive difficulty adjustment.
 */
export const sessionPerformance = mysqlTable("session_performance", {
  id: int("id").autoincrement().primaryKey(),
  /** Foreign key reference to the learning session */
  sessionId: varchar("sessionId", { length: 64 }).notNull().unique(),
  /** Total number of problems attempted */
  totalProblems: int("totalProblems").default(0).notNull(),
  /** Number of correct answers */
  correctAnswers: int("correctAnswers").default(0).notNull(),
  /** Current difficulty level based on performance */
  currentDifficulty: mysqlEnum("currentDifficulty", ["easy", "medium", "hard"]).default("medium").notNull(),
  /** Timestamp of last activity */
  lastActivityAt: timestamp("lastActivityAt").defaultNow().notNull(),
  /** Timestamp when the record was created */
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  /** Timestamp when the record was last updated */
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SessionPerformance = typeof sessionPerformance.$inferSelect;
export type InsertSessionPerformance = typeof sessionPerformance.$inferInsert;
